### ISSUE TITLE
[topic lin & win] Flickering observed while using gst-play playlist if previous file played is MPEG

### ISSUE THREAD

**Issue by kuhanh91** [intel/gstreamer-media-SDK#61]
gstreamer framework: 1.12.3
gst-msdk : topic_linux_and_window
environment: linux (wayland weston and X11 DRI3)

In gst-play-1.0, playing a high frame rate video after a MPEG file causes an out of surface issue from MSDK.

Increasing the surfaces number for the GST MSDK decoder task will solve the problem.

The commit id e476a37 in master branch fixes this issue and needs to be ported.

[HSD-ES: 1504535288]

**Comment by ishmael1985** [comment]
Can you share the MPEG video file in question?

**Comment by SiewHoon** [comment]
The flickering happened at this IU.mkv video file after play MPEG2 video.
command: gst-play-1.0 --playlist custom.m3u

MPEG2 video : MPEG-1 System_mpg_MPEG-2_Simple Profile-Main Profile_320x240_3007Kbps_24.000fps.mpeg

**Comment by ishmael1985** [comment]
Could you also please share the IU.mkv video? Can't replicate the bug..

**Comment by ishmael1985** [comment]
@kuhanh91 @SiewHoon , I still can't reproduce this issue. Does this issue still exist in the latest GST-MFX version in the topic branch?

**Comment by kuhanh91** [comment]
The issue is resolved in topic branch after porting the commit id e476a37 from master branch. The commit id for topic branch is 4971500a49bca8968d9bb62947915d8600f431b1

**Comment by ishmael1985** [comment]
The proposed fix is a hack for just 2 clips, and this issue could probably be related to #58. Nevertheless, can you help share the clips so that we can reproduce the issue on our side?

**Comment by SiewHoon** [comment]
Different issue. thanks.

**Comment by ishmael1985** [comment]
@kuhanh91 does the issue still exist when testing from here? https://github.com/ishmael1985/gstreamer-media-SDK
Please close the issue once the issue is resolved.

**Comment by SiewHoon** [comment]
The video corruption observed when playing AVSEQ01_MPEG.DAT video clip in latest topic_linux_and_window branch.
